# Generated by Django 3.0.3 on 2020-02-28 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=50)),
                ('mathScore', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('physicsScore', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('chemistryScore', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('biologyScore', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
